### ISSUE TITLE
assert len(response['Images']) == 1 failed 

### ISSUE THREAD

**Issue by wangxuedi** [CSL-KU/firesim-nvdla#1]
When i follow the steps, and run `firesim launchrunfarm`, occured an error as follows:
![image](https://user-images.githubusercontent.com/42477429/55090749-9c845b80-50ea-11e9-8e95-60f2dd9dc4f0.png)

**Comment by farzad64** [comment]
Could you copy the last couple of lines from the log file, where the error occurs, here?

**Comment by wangxuedi** [comment]
The last couple of lines from the log file just like follows, thanks for your patience.
![image](https://user-images.githubusercontent.com/42477429/55122626-8605f080-513a-11e9-8032-198d595db4e7.png)

**Comment by farzad64** [comment]
@wangxuedi I'm not sure why this is happening. Have you tried running with `defaulthwconfig=firesim-quadcore-nic-ddr3-llc4mb`?

@sagark Do you know why is this happening? `firesim-nvdla` is forked from version 1.4 and it does not make any changes to the deployment commands.

**Comment by sagark** [comment]
I tried running the chunk of code that's failing in a separate interpreter with the f1_ami_name from 1.4 and I get a correct result. 

@wangxuedi can you tell us a bit about your environment? Which region are you running in? Are you manually able to run the following snippet in a python2 interpreter on your aws instance?

```
import boto3
import botocore
f1_ami_name = "FPGA Developer AMI - 1.4.0 - pre8-40257ab5-6688-4c95-97d1-e251a40fd1fc-ami-0335b86e84e820e8d.4"
def get_f1_ami_id():
    """ Get the AWS F1 Developer AMI by looking up the image name -- should be region independent.
    """
    client = boto3.client('ec2')
    response = client.describe_images(Filters=[{'Name': 'name', 'Values': [f1_ami_name]}])
    assert len(response['Images']) == 1
    return response['Images'][0]['ImageId']



get_f1_ami_id()
```

When doing so, I get the correct response for the `us-west-2` region, which is: `'ami-cfe89eb7'`

**Comment by wangxuedi** [comment]
@farzadfch  I'm running with defaulthwconfig=firesim-quadcore-no-nic-nvdla-ddr3-llc4mb.

**Comment by wangxuedi** [comment]
@farzadfch 
/home/centos/firesim-nvdla/deploy/config_runtime.ini like follows.

![image](https://user-images.githubusercontent.com/42477429/55131932-95e1fc80-515b-11e9-8574-bdcc8b914b80.png)

**Comment by wangxuedi** [comment]
The region is us-east-1

"Traceback (most recent call last):
  File "test.py", line 14, in <module>
    get_f1_ami_id()
  File "test.py", line 9, in get_f1_ami_id
    assert len(response['Images']) == 1
AssertionError"

**Comment by wangxuedi** [comment]
'Traceback (most recent call last):
  File "test.py", line 14, in <module>
    get_f1_ami_id()
  File "test.py", line 9, in get_f1_ami_id
    assert len(response['Images']) == 1
AssertionError'

**Comment by wangxuedi** [comment]
The region is us-east-1.
When I run the snippet, occured the error as follows:
![image](https://user-images.githubusercontent.com/42477429/55132438-6502c700-515d-11e9-98a3-912e77c9eec9.png)

**Comment by sagark** [comment]
If you go here, are you able to see 1.4.0 as an option in the drop-down
menu?

https://aws.amazon.com/marketplace/server/configuration?productId=40257ab5-6688-4c95-97d1-e251a40fd1fc&ref_=psb_cfg_continue

Is your manager also running on the 1.4.0 AMI?

**Comment by wangxuedi** [comment]
I can not. I just see the 1.5.0 and 1.6.0.

**Comment by farzad64** [comment]
So if I've understood correctly the reason you get this error is `firesim-nvdla` needs 1.4.0 AMI and you don't have access to it.

@sagark does merging the latest changes from `firesim` repo fix this issue? Is there also a temporary fix that he can try before I get the chance to merge stuff?

**Comment by sagark** [comment]
Yeah, it seems that Amazon doesn't make the older versions available to users if they subscribe to the FPGA Dev AMI after they're deprecated. What we'll probably start doing on mainline FireSim to address this in the future is to just ship a custom AMI based on each FPGA Dev AMI that we'll leave up on the AWS Marketplace. 

In the meantime I think you can do one of two things -- make your own public AMI based on 1.4.0 to share with @wangxuedi, or merge upstream firesim master (which uses 1.5.0 AMI now).

**Comment by farzad64** [comment]
@sagark thanks a lot for your help!

@wangxuedi I'm working on merging from the firesim upstream which uses 1.5.0 AMI. This should fix the issue. I'll come back to you soon.

**Comment by farzad64** [comment]
@wangxuedi unfortunately, after merging with firesim upstream, the build terminates because of a Vivado bug :( resolving this may require more time.

To get around the AMI version issue for now, I made my own AMI based on 1.4.0 as Sagar suggested. Unfortunately, Amazon does not allow me to set my AMI permission to public because it's based on a Marketplace AMI. If you send me your AWS Account Number, I can give permission to you so you can access it.

**Comment by farzad64** [comment]
I was finally able to build the AGFI with the latest FireSim upstream and I pushed my changes. @wangxuedi try doing a fresh clone. The issue that you had with `firesim launchrunfarm` must be fixed now.
