### ISSUE TITLE
Link broken of get-darknet.sh

### ISSUE THREAD

**Issue by franktaTian** [CSL-KU/firesim-nvdla#31]
I  tried build firesim FPGA on an U250 board with nvdla small and large. but when I tried to run get-darknet.sh.The link seems broken.
--2022-12-19 09:02:45--  http://www.ittc.ku.edu/~farshchi/darknet-nvdla.tar.gz
Resolving www.ittc.ku.edu (www.ittc.ku.edu)... 129.237.125.27
Connecting to www.ittc.ku.edu (www.ittc.ku.edu)|129.237.125.27|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-19 09:02:46 ERROR 404: Not Found.

And as a result , I cannot run solo.sh to replay something.

**Comment by farzad64** [comment]
The broken link is temporarily restored. Can you try again?

**Comment by franktaTian** [comment]
Yes! I can download it now! Thanks very much .
