### ISSUE TITLE
Connecting to 169.254.169.254:80... failed: Connection timed out when run ./build-setup.sh fast

### ISSUE THREAD

**Issue by speedzheng** [CSL-KU/firesim-nvdla#4]
keep hitting the error message then tried to look for the solution for the similar issue but still not fixed. I guess that it may be related my setup but can't figure where it is so have to raise it up. Thanks!

**Comment by farzad64** [comment]
Are you running on Amazon AWS? or your local machine?

**Comment by speedzheng** [comment]
I don't know. I just load the tree then run the command on my local machine.

**Comment by speedzheng** [comment]
I just redo everything but still hit the same thing. So it doesn't look like my environment issue but the build flow issue. could someone help me? Thanks!

**Comment by farzad64** [comment]
FireSim-NVDLA is not supposed to work on your local machine! It runs on AWS EC2. If you follow the instructions on the README, it directs you to the correct version of the FireSim documentation which guides you on how to set up an AWS account and configure it.
