### ISSUE TITLE
about unsupported layers in YOLO

### ISSUE THREAD

**Issue by cnjsdfcy** [CSL-KU/firesim-nvdla#7]
Hi Farzad,
1. How do you compose the loadable file for YOLO? NVDLA compiler will report errors when encounter unsupported layers.
2. After you get the loadable file, how do you dispatch these unsupported layers to RISC-V processor? I checked the KMD src, it seems that you did not modify the scheduler.

Thanks,
Caiyu

**Comment by farzad64** [comment]
This is done by @prasshantg. Darknet already has the implementation for the YOLO in C code, and as far as I know, we are using the Darknet implementation for the unsupported layers and run them on the RISC-V processor.

**Comment by cnjsdfcy** [comment]
Thank you for your response, Farzad.
I found [this issue](https://github.com/prasshantg/odla_data/issues/2), seems that others also wonder how three separated nvdla loadable files were generated.

**Comment by cnjsdfcy** [comment]
close thanks to Prashant's [answer](https://github.com/prasshantg/odla_data/issues/2#issuecomment-548481097).
