### ISSUE TITLE
question about f1

### ISSUE THREAD

**Issue by lznnnnn1998** [CSL-KU/firesim-nvdla#8]
how to copy files from the linux system on f1 ( which i  screen fsim0 to)  to my manager instance

**Comment by farzad64** [comment]
You can add the `outputs` option to `darknet-nvdla.json`. For example. if you add `"outputs" : [ "/root/mydir/" ],` it copies the entire `/root/mydir` directory to the manager under the workload results directory.

For more information, please take a look at the FireMarshal's documentation: [https://docs.fires.im/en/1.6.0/Advanced-Usage/FireMarshal/FireMarshal-Config.html](https://docs.fires.im/en/1.6.0/Advanced-Usage/FireMarshal/FireMarshal-Config.html)

**Comment by lznnnnn1998** [comment]
i modified darknet-nvdla.json like this:
{
        "benchmark_name": "darknet-nvdla",
        "common_simulation_outputs": [
                "uartlog",
                "/root/darknet-nvdla/predictions.png",
                "/root/darknet-nvdla"
        ],
        "outputs":["/root/darknet-nvdla"],
        "common_bootbinary": "../../../sw/firesim-software/images/darknet-nvdla-bin",
        "common_rootfs": "../../../sw/firesim-software/images/darknet-nvdla.img"
}
and i  do `firesim runworkload` . but only `uartlog` is copied in `results-workloads`

**Comment by farzad64** [comment]
Did you do a `marshal install`?

**Comment by lznnnnn1998** [comment]
oh, i  re-edit it, changing `outputs` to `common_output`. and then get the files.
thank you for helping me so many times!!!!
