### ISSUE TITLE
./solo.sh: line 2:   119 Segmentation fault

### ISSUE THREAD

**Issue by lznnnnn1998** [CSL-KU/firesim-nvdla#9]
when i tried yolo3, i got this. i think it's about nvdla
# cd darknet-nvdla/
# ./solo.sh
learning_rate: Using default '0.001000'
momentum: Using default '0.900000'
decay: Using default '0.000100'
policy: Using default 'constant'
max_batches: Using default '0'
layer     filters    size              input                output
    0 offset: Using default '0.000000'
shifter: Using default '0'
post_offset: Using default '0.000000'
post_scale: Using default '1.000000'
outputs 692224 num_out 5537792
    1 libnvdla<1> failed to open dla device
libnvdla<1> Out of bounds DLA instance 0 requested.
[    1.268000] darknet[119]: unhandled signal 11 code 0x1 at 0x0000000000000008 in libnvdla_runtime.so[200028f000+35000]
[    1.268000] CPU: 0 PID: 119 Comm: darknet Tainted: G        W        4.15.0-rc6-gafc1699e27a4 #1
[    1.268000] sepc: 00000020002ab710 ra : 000000200002515c sp : 0000003fffad21b0
[    1.268000]  gp : 00000000000322a8 tp : 000000200060f5b0 t0 : 0000002000022aa0
[    1.268000]  t1 : 0000002000025144 t2 : ffffffffffffffff s0 : 00000000000842f0
[    1.272000]  s1 : 0000000000000000 a0 : 0000000000000000 a1 : 0000003fffad21bc
[    1.272000]  a2 : 00000000003cac70 a3 : 00000000009b2840 a4 : 0000000000000000
[    1.272000]  a5 : 00000020002ab6b8 a6 : 0000000000e71250 a7 : 00000020002c61a8
[    1.272000]  s2 : 000000000077a649 s3 : 0000003fffad23a8 s4 : 0000003fffad23a8
[    1.272000]  s5 : 000000000004e500 s6 : 0000000000000004 s7 : 00000000000001a0
[    1.272000]  s8 : 00000000000001a0 s9 : 00000000000001a0 s10: 0000000000000004
[    1.272000]  s11: 00000000000a9000 t3 : 0000000000001144 t4 : 0000000000000002
[    1.272000]  t5 : 0000000000000002 t6 : 0000000000000000
[    1.272000] sstatus: 8000000200006020 sbadaddr: 0000000000000008 scause: 000000000000000d
./solo.sh: line 2:   119 Segmentation fault      ./darknet detect yolov3-odla.cfg yolov3-odla.cfg data/person.jpg

**Comment by farzad64** [comment]
Make sure `defaulthwconfig`  is set to `firesim-quadcore-no-nic-nvdla-ddr3-llc4mb`.
